# FROM gradle:8.13-jdk17 AS build
# WORKDIR /app
# COPY . .
# RUN gradle build bootrun

FROM openjdk:17-jdk
WORKDIR /app
COPY build/libs/*.jar app.jar
CMD ["java", "-jar", "app.jar"]

# FROM gradle:8.13-jdk17 AS build
# WORKDIR /app
# COPY . .
# RUN gradle clean bootJar -x test
#
# FROM eclipse-temurin:17-jdk-focal
# WORKDIR /app
# RUN apt-get update && apt-get install -y ca-certificates
#
# COPY gradlew build.gradle settings.gradle ./
# COPY gradle ./gradle
#
# RUN ./gradlew dependencies --no-daemon || true
#
# COPY src ./src
# EXPOSE 8080
#
# CMD ["./gradlew", "bootRun"]